=== Errafita365/1DAM_LMSGI_Rafa/Tema 11/Ejemplo 3/concesonario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="concesonario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="matricula" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"></xs:element>
                            <xs:element name="modelo" type="xs:string"></xs:element>
                            
                            <xs:choice>
                            <xs:element name="cilindrada" type="xs:decimal"></xs:element>
                            <xs:element name="caballos" type="xs:string"></xs:element>
                            </xs:choice>

                            <xs:element name="combustible" type="xs:string"></xs:element>
                            <xs:element name="precio" type="xs:decimal"></xs:element>
                            <xs:element name="año" type="xs:unsignedShort" minOccurs="0"></xs:element>
                            <xs:element name="color" type="xs:string"></xs:element>
                            <xs:element name="interesado" type="xs:string" maxOccurs="unbounded" minOccurs="0"></xs:element>
                            
                        



                        </xs:sequence>
                            <xs:attribute name="matricula" type="xs:string" use="required"></xs:attribute>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="provincia" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Errafita365/1DAM_LMSGI_Rafa/Tema 11/Ejemplo 3/concesonario.xml
<?xml version="1.0" encoding="UTF-8"?>
<concesonario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="concesonario.xsd" provincia="Malaga">

<coche matricula="6732KPC">
    <marca>Seat</marca>
    <modelo>Ateca</modelo>
    <cilindrada>1.7</cilindrada>
    <combustible>Diesel</combustible>
    <precio>23.000€</precio>
    <año>2018</año>
    <color>negro</color>
    <interesado>33358697A</interesado>
    <interesado>30515455Y</interesado>
</coche>

<coche matricula="789099P">
    <marca> Volkswaguen</marca>
    <modelo>Polo</modelo>
    <cilindrada>1.2</cilindrada>
    <combustible>Gasolina</combustible>
    <precio>5.000€</precio>
    <color>rojo</color>
    <interesado>87667780L</interesado>
</coche>

<coche matricula="8765DGH">
    <marca>Renault</marca>
    <modelo>Megane</modelo>
    <caballos>120</caballos>
    <combustible>Diesel</combustible>
    <precio>7.500€</precio>
    <color>verde</color>
    
</coche>


</concesonario>
